name = "FrictionProviders"
uuid = "0e168e98-d76b-4d03-b07e-2b13986b2fd0"
authors = ["wgst <wch.stark@gmail.com> and contributors"]
version = "0.1.7"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NQCBase = "78c76ebc-5665-4934-b512-82d81b5cbfb7"
NQCModels = "c814dc9f-a51f-4eaf-877f-82eda4edad48"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[sources]
NQCModels = {rev = "remove-python", url = "../NQCModels.jl"}
ACEpotentials={url="https://github.com/ACEsuit/ACEpotentials.jl.git", rev="v0.6.5"} # Or install ACEsuit/ACEregistry

[compat]
JuLIP = "0.13, 0.14"
NQCBase = "0.2, 0.3, 0.4"
NQCModels = "0.9"
PythonCall = "0.9"
StaticArrays = "1"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53" # v0.6.5
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test", "Random", "ACEpotentials"]
